# SPDX-FileCopyrightText: Copyright (c) 2025-2026 Max Trunnikov
# SPDX-License-Identifier: MIT

version = 1
[[annotations]]
path = [
    ".DS_Store",
    ".gitignore",
    ".pdd",
    "**.json",
    "**.md",
    "**.png",
    "**.svg",
    "**.txt",
    "**/.DS_Store",
    "**/.gitignore",
    "**/.pdd",
    "**/*.csv",
    "**/*.jpg",
    "**/*.json",
    "**/*.md",
    "**/*.pdf",
    "**/*.png",
    "**/*.svg",
    "**/*.txt",
    "**/*.vm",
    "README.md",
    ".eslintrc",
    ".gitattributes",
    ".markdownlint.json",
    "npmignore",
    "package-lock.json",
    "package.json",
    "patches/grunt-mocha-cli+7.0.0.patch",
    "renovate.json",
    ".npmignore",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2025-2026 Max Trunnikov"
SPDX-License-Identifier = "MIT"