# SPDX-FileCopyrightText: Copyright (c) 2025 Max Trunnikov
# SPDX-License-Identifier: MIT
---
name: copyrights
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  copyrights:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: yegor256/copyrights-action@0.0.8
