# SPDX-FileCopyrightText: Copyright (c) 2025-2026 Max Trunnikov
# SPDX-License-Identifier: MIT
---
name: pr-size
'on': pull_request
jobs:
  pr-size:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: maidsafe/pr_size_checker@v3
        with:
          target_branch: master
          max_lines_changed: 350
